### PR TITLE
propose single-app architecture

### LINKED ISSUE #1: App Architecture
I think it makes sense to have one `exr-tools` crate, because it's easier to use. It would also be possible to have multiple tools, like `compression-stats` and `get-meta` and `set-meta`, but it would be a little more work for the user to select and install the right one.

### PR DESCRIPTION
**Pull request by johannesvollmer**
@Narann

### CODE REVIEW

**Comment by Narann** [comment]
Thanks, do we really need the `Cargo.lock`?

**Comment by johannesvollmer** [comment]
I don't know. I forgot. Is it common practice to include the lock file in the repository? I don't have an opinion on that. If you like, we gitignore it.

**Comment by johannesvollmer** [comment]
What do you think about the approach in general? Would you like to have individual crates or one single app?

**Comment by Narann** [comment]
About the `Cargo.lock`, looks like [it's recommended](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html) to keep it for binaries, but not libraries. So it make sense.

Having coding my own prototype privately, I realize it's simpler to have single command line application (I can't send archive via github, I will need your mail, mine is `fevrier(dot)dorian(at)yahoo(dot)fr`).

image

Here is my help message, so you can see how it could work (kinda like `git`):

``` text
usage: ppexr [--help] <command> [options]

Options:
    -h, --help     Print this message.
    -v, --version  Print versions information of this program and its
                   dependencies.

Commands:
    header         Print OpenEXR image file's header in various formats.
    create         TODO

header:
    By default this command prints image file header information in a human
    readable format.

    Usage:
      ppexr header [options] file [file...]
      ppexr header foo.exr
      ppexr header --json bar.exr

    Options:
      -j, --json  Print image file header information in JSON format.

    Examples:
      ppexr header foo.exr
      ppexr header --json bar.exr

create:
    Create an empty EXR image file.

    Usage:
      ppexr create --width 512 --height 512 destination.exr

    Options:
      -w, --width   Layer width.
      -h, --height  Layer height.

    Examples:
      ppexr create -w 512 -h 512 foo.exr
```

I didn't use dedicated library for argument parsing because it took a *lot* of strings into the final binary. rust is notorious for generating heavy binaries event if 99 % of data is not required/wanted.

**Comment by johannesvollmer** [comment]
> I didn't use dedicated library for argument parsing because it took a lot of strings into the final binary. rust is notorious for generating heavy binaries event if 99 % of data is not required/wanted.

Does this really matter if we already include the 200KB exrs dependency with a ton of strings in it? :D

---

> simpler to have single command line application

Yeah, I agree, as a user I don't want to install five different tools for my exr manipulation haha. 

> I can't send archive via github

How about we merge this basic PR when the discussion is resolved, and then you insert your code, using another pull request? The code I inserted is only a placeholder, the important part is the file/folder structure :)

---

> help message, so you can see how it could work (kinda like git)

Looks nice so far! Although I would like to rename some items at a later stage, but this can be discussed elsewhere

**Comment by Narann** [comment]
> Does this really matter if we already include the 200KB exrs dependency with a ton of strings in it? :D

On a professional side, I have no objection to favor the best economical/time ratio, so overstacking is the norm, but I'm kinda surprised of seeing the same trend on the FOSS ecosystem.

I suspect it's because many FOSS contributors nowadays are JS/Python devs (I'm a Python dev) used to `npm`/`pip` all around for frameworks. Adding a feature to an existing project is basically adding a line to `requirement.txt`, and write few lines in the project. Having the opportunity to work with high quality `C` project, I have the impression that delivery binary data that are not used at all, just weird.

I'm kinda alone to think this and I understand the excitement with playing with new tools, we dev on our spare time after all. In this case, argument parsing like this was just my personal taste. I have no problem using a dedicated framework like `clap`.

> How about we merge this basic PR when the discussion is resolved, and then you insert your code, using another pull request? The code I inserted is only a placeholder, the important part is the file/folder structure :)

OK, no problem.

**Comment by johannesvollmer** [comment]
Interesting. The trend to have too many dependencies is well known, especially with npm. The only reason I would choose to use a library for this is that it would save me a lot of code and typing. I suppose you already have the logic written in your private repository, so I would just choose yours. 

If there are no more points to discuss about the project structure, we can merge this pr, and then you can contribute your code :)

**Pull request merged**
